part of '../../migrate.dart';

/// Creates a new schema. Applications should execute the resulting SQL through
/// reviewed migrations; this does not inspect or mutate an existing database.
List<SqlCommand> createSchema(List<TableSchema> tables, SqlDialect dialect) {
  final commands = <SqlCommand>[];
  final names = <String>{};
  for (final table in tables) {
    if (!names.add(table.name)) {
      throw const OrmException('SCHEMA.DUPLICATE', 'Duplicate table name.');
    }
    final columns = <String>{};
    for (final column in table.columns) {
      if (!columns.add(column.name)) {
        throw const OrmException('SCHEMA.DUPLICATE', 'Duplicate column name.');
      }
    }
    for (final key in [
      table.primaryKey,
      ...table.uniqueKeys,
      ...table.indexes.map((i) => i.columns),
    ]) {
      if (key.any((name) => !columns.contains(name))) {
        throw const OrmException(
          'SCHEMA.KEY',
          'Key references an unknown column.',
        );
      }
    }
    final generated = table.columns.where((c) => c.generated).toList();
    if (generated.length > 1 ||
        generated.any(
          (c) =>
              c.codec.sqlType != 'integer' ||
              c.nullable ||
              table.primaryKey.length != 1 ||
              table.primaryKey.single != c.name,
        )) {
      throw const OrmException(
        'SCHEMA.IDENTITY',
        'Identity requires a non-null single integer primary key.',
      );
    }
    final definitions = <String>[];
    for (final c in table.columns) {
      final identity = c.generated;
      final type = _storageType(c.codec.sqlType, dialect);
      final b = StringBuffer('${_quote(c.name)} $type');
      if (identity) {
        b.write(
          dialect == SqlDialect.sqlite
              ? ' PRIMARY KEY'
              : ' GENERATED BY DEFAULT AS IDENTITY',
        );
      }
      if (!c.nullable) b.write(' NOT NULL');
      if (c.defaultSql case final value?) b.write(' DEFAULT ($value)');
      definitions.add(b.toString());
    }
    if (table.primaryKey.isNotEmpty &&
        !(dialect == SqlDialect.sqlite && generated.isNotEmpty)) {
      definitions.add(
        'PRIMARY KEY (${table.primaryKey.map(_quote).join(', ')})',
      );
    }
    for (final key in table.uniqueKeys) {
      definitions.add('UNIQUE (${key.map(_quote).join(', ')})');
    }
    if (dialect == SqlDialect.sqlite) {
      for (final key in table.foreignKeys) {
        definitions.add(_foreignKey(key));
      }
    }
    commands.add(
      SqlCommand(
        'CREATE TABLE ${_quote(table.name)} (${definitions.join(', ')})',
      ),
    );
  }
  if (dialect == SqlDialect.postgres) {
    // Creating constraints after all tables also supports cycles and self links.
    for (final table in tables) {
      for (final key in table.foreignKeys) {
        commands.add(
          SqlCommand(
            'ALTER TABLE ${_quote(table.name)} ADD ${_foreignKey(key)}',
          ),
        );
      }
    }
  }
  for (final table in tables) {
    for (final index in table.indexes) {
      commands.add(
        SqlCommand(
          'CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${_quote(index.name)} '
          'ON ${_quote(table.name)} (${index.columns.map(_quote).join(', ')})',
        ),
      );
    }
  }
  return List.unmodifiable(commands);
}

String _foreignKey(ForeignKey key) {
  if (key.columns.isEmpty ||
      key.columns.length != key.targetColumns.length ||
      !{
        'RESTRICT',
        'NO ACTION',
        'CASCADE',
        'SET NULL',
        'SET DEFAULT',
      }.contains(key.onDelete)) {
    throw const OrmException(
      'SCHEMA.FOREIGN_KEY',
      'Invalid foreign key declaration.',
    );
  }
  return 'FOREIGN KEY (${key.columns.map(_quote).join(', ')}) REFERENCES ${_quote(key.target)} '
      '(${key.targetColumns.map(_quote).join(', ')}) ON DELETE ${key.onDelete}';
}

String _storageType(String type, SqlDialect dialect) => switch ((
  dialect,
  type,
)) {
  (SqlDialect.sqlite, 'integer') => 'INTEGER',
  (SqlDialect.sqlite, 'bigint' || 'text' || 'timestamp' || 'json') => 'TEXT',
  (SqlDialect.sqlite, 'boolean') => 'INTEGER',
  (SqlDialect.sqlite, 'real') => 'REAL',
  (SqlDialect.sqlite, 'blob') => 'BLOB',
  (SqlDialect.postgres, 'integer') => 'BIGINT',
  (SqlDialect.postgres, 'bigint') => 'NUMERIC',
  (SqlDialect.postgres, 'text') => 'TEXT',
  (SqlDialect.postgres, 'real') => 'DOUBLE PRECISION',
  (SqlDialect.postgres, 'boolean') => 'BOOLEAN',
  (SqlDialect.postgres, 'timestamp') => 'TIMESTAMPTZ',
  (SqlDialect.postgres, 'json') => 'JSONB',
  (SqlDialect.postgres, 'blob') => 'BYTEA',
  _ => throw OrmException('SCHEMA.TYPE', 'No $dialect mapping for $type.'),
};

/// Actual catalog columns, rather than a claimed migration version.
final class ColumnInfo {
  final String name;
  final String storageType;
  final bool nullable;
  final String? defaultSql;
  final bool generated;
  const ColumnInfo({
    required this.name,
    required this.storageType,
    required this.nullable,
    this.defaultSql,
    this.generated = false,
  });
}

Future<List<ColumnInfo>> inspectColumns(
  Database<Backend> db,
  String table,
) async {
  if (db.dialect == SqlDialect.sqlite) {
    final rows = await db.execute(
      SqlCommand('PRAGMA table_xinfo(${_quote(table)})'),
    );
    return [
      for (final row in rows.rows)
        ColumnInfo(
          name: row[1] as String,
          storageType: (row[2] as String).toUpperCase(),
          nullable: row[3] == 0 && row[5] == 0,
          defaultSql: row[4] as String?,
          generated: (row[6] as int) > 0,
        ),
    ];
  }
  final result = await db.execute(
    SqlCommand(
      '''
SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod),
       NOT a.attnotnull, pg_get_expr(d.adbin, d.adrelid),
       a.attidentity <> '' OR a.attgenerated <> ''
FROM pg_catalog.pg_attribute a
JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE c.relname = \$1 AND n.nspname = current_schema() AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum''',
      [table],
    ),
  );
  return [
    for (final row in result.rows)
      ColumnInfo(
        name: row[0] as String,
        storageType: (row[1] as String).toUpperCase().replaceAll(
          'TIMESTAMP WITH TIME ZONE',
          'TIMESTAMPTZ',
        ),
        nullable: row[2] as bool,
        defaultSql: row[3] as String?,
        generated: row[4] as bool,
      ),
  ];
}

/// Column drift check. Constraints, indexes and unmanaged objects are separate
/// catalog checks; this method does not pretend that columns prove full equality.
Future<List<String>> verifyColumns(
  Database<Backend> db,
  List<TableSchema> tables,
) async {
  final differences = <String>[];
  for (final table in tables) {
    final actual = {
      for (final c in await inspectColumns(db, table.name)) c.name: c,
    };
    for (final expected in table.columns) {
      final column = actual.remove(expected.name);
      final path = '${table.name}.${expected.name}';
      if (column == null) {
        differences.add('$path is missing');
        continue;
      }
      if (column.storageType !=
          _storageType(expected.codec.sqlType, db.dialect)) {
        differences.add('$path type is ${column.storageType}');
      }
      if (column.nullable != expected.nullable) {
        differences.add('$path nullability differs');
      }
    }
    for (final extra in actual.keys) {
      differences.add('${table.name}.$extra is unmanaged');
    }
  }
  return differences;
}
