part of '../../migrate.dart';

/// Creates a new schema. Applications should execute the resulting SQL through
/// reviewed migrations; this does not inspect or mutate an existing database.
List<SqlCommand> createSchema(List<TableSchema> tables, SqlDialect dialect) {
  final commands = <SqlCommand>[];
  final names = <String>{};
  for (final table in tables) {
    if (!names.add(table.name)) {
      throw const OrmException('SCHEMA.DUPLICATE', 'Duplicate table name.');
    }
    final columns = <String>{};
    for (final column in table.columns) {
      if (column.decimalPrecision != null || column.decimalScale != null) {
        if (column.codec.sqlType != 'decimal' ||
            column.decimalPrecision == null ||
            column.decimalPrecision! < 1 ||
            column.decimalPrecision! > 1000 ||
            (column.decimalScale ?? 0) < -1000 ||
            (column.decimalScale ?? 0) > 1000) {
          throw const OrmException(
            'SCHEMA.DECIMAL_DIGITS',
            'Decimal precision must be 1..1000 and scale -1000..1000 on a decimal column.',
          );
        }
      }
      if (column.integerBits != null &&
          (column.codec.sqlType != 'integer' ||
              !{16, 32, 64}.contains(column.integerBits))) {
        throw const OrmException(
          'SCHEMA.INTEGER_BITS',
          'Integer width must be 16, 32 or 64 on an integer column.',
        );
      }
      if (!columns.add(column.name)) {
        throw const OrmException('SCHEMA.DUPLICATE', 'Duplicate column name.');
      }
    }
    for (final key in [
      table.primaryKey,
      ...table.uniqueKeys,
      ...table.indexes.map((i) => i.columns),
    ]) {
      if (key.any((name) => !columns.contains(name))) {
        throw const OrmException(
          'SCHEMA.KEY',
          'Key references an unknown column.',
        );
      }
    }
    final generated = table.columns.where((c) => c.generated).toList();
    if (generated.length > 1 ||
        generated.any(
          (c) =>
              c.codec.sqlType != 'integer' ||
              c.nullable ||
              table.primaryKey.length != 1 ||
              table.primaryKey.single != c.name,
        )) {
      throw const OrmException(
        'SCHEMA.IDENTITY',
        'Identity requires a non-null single integer primary key.',
      );
    }
    commands.add(SqlCommand(_createTable(table, dialect)));
  }
  if (dialect == SqlDialect.postgres) {
    // Creating constraints after all tables also supports cycles and self links.
    for (final table in tables) {
      for (final key in table.foreignKeys) {
        commands.add(
          SqlCommand(
            'ALTER TABLE ${_quote(table.name)} ADD ${_foreignKey(key)}',
          ),
        );
      }
    }
  }
  for (final table in tables) {
    for (final index in table.indexes) {
      commands.add(
        SqlCommand(
          'CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${_quote(index.name)} '
          'ON ${_quote(table.name)} (${index.columns.map(_quote).join(', ')})',
        ),
      );
    }
  }
  return List.unmodifiable(commands);
}

String _createTable(TableSchema table, SqlDialect dialect, {String? name}) {
  final definitions = <String>[];
  for (final c in table.columns) {
    definitions.add(_columnDefinition(c, dialect));
  }
  if (table.primaryKey.isNotEmpty &&
      !(dialect == SqlDialect.sqlite &&
          table.columns.any((c) => c.generated))) {
    definitions.add('PRIMARY KEY (${table.primaryKey.map(_quote).join(', ')})');
  }
  for (final key in table.uniqueKeys) {
    definitions.add('UNIQUE (${key.map(_quote).join(', ')})');
  }
  if (dialect == SqlDialect.sqlite) {
    for (final key in table.foreignKeys) {
      definitions.add(_foreignKey(key));
    }
  }

  return 'CREATE TABLE ${_quote(name ?? table.name)} (${definitions.join(', ')})';
}

String _columnDefinition(Column<Object?> c, SqlDialect dialect) {
  final b = StringBuffer('${_quote(c.name)} ${_columnStorageType(c, dialect)}');
  if (dialect == SqlDialect.sqlite && c.codec.sqlType == 'decimal') {
    b.write(' COLLATE "orm_decimal_v1"');
  }
  if (c.generated) {
    b.write(
      dialect == SqlDialect.sqlite
          ? ' PRIMARY KEY'
          : ' GENERATED BY DEFAULT AS IDENTITY',
    );
  }
  if (!c.nullable) b.write(' NOT NULL');
  if (c.defaultSql case final value?) {
    b.write(' DEFAULT (${_coerceColumn(value, c, dialect)})');
  }
  if (dialect == SqlDialect.sqlite && c.decimalPrecision != null) {
    b.write(
      ' CHECK (${_decimalCheck(c.name, c.decimalPrecision!, c.decimalScale ?? 0)})',
    );
  }
  if (dialect == SqlDialect.sqlite &&
      c.integerBits != null &&
      c.integerBits != 64) {
    b.write(' CHECK (${_integerCheck(c.name, c.integerBits!)})');
  }
  return b.toString();
}

String _createIndex(String table, IndexSchema index) =>
    'CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${_quote(index.name)} '
    'ON ${_quote(table)} (${index.columns.map(_quote).join(', ')})';

String _foreignKey(ForeignKey key) {
  if (key.columns.isEmpty ||
      key.columns.length != key.targetColumns.length ||
      !{
        'RESTRICT',
        'NO ACTION',
        'CASCADE',
        'SET NULL',
        'SET DEFAULT',
      }.contains(key.onDelete)) {
    throw const OrmException(
      'SCHEMA.FOREIGN_KEY',
      'Invalid foreign key declaration.',
    );
  }
  return 'FOREIGN KEY (${key.columns.map(_quote).join(', ')}) REFERENCES ${_quote(key.target)} '
      '(${key.targetColumns.map(_quote).join(', ')}) ON DELETE ${key.onDelete}';
}

String _storageType(String type, SqlDialect dialect) =>
    switch ((dialect, type)) {
      (SqlDialect.sqlite, 'integer') => 'INTEGER',
      (
        SqlDialect.sqlite,
        'bigint' || 'text' || 'timestamp' || 'json' || 'decimal',
      ) =>
        'TEXT',
      (SqlDialect.sqlite, 'boolean') => 'INTEGER',
      (SqlDialect.sqlite, 'real') => 'REAL',
      (SqlDialect.sqlite, 'blob') => 'BLOB',
      (SqlDialect.postgres, 'integer') => 'BIGINT',
      (SqlDialect.postgres, 'bigint' || 'decimal') => 'NUMERIC',
      (SqlDialect.postgres, 'text') => 'TEXT',
      (SqlDialect.postgres, 'real') => 'DOUBLE PRECISION',
      (SqlDialect.postgres, 'boolean') => 'BOOLEAN',
      (SqlDialect.postgres, 'timestamp') => 'TIMESTAMPTZ',
      (SqlDialect.postgres, 'json') => 'JSONB',
      (SqlDialect.postgres, 'blob') => 'BYTEA',
      _ => throw OrmException('SCHEMA.TYPE', 'No $dialect mapping for $type.'),
    };

String _columnStorageType(Column<Object?> column, SqlDialect dialect) =>
    dialect == SqlDialect.postgres &&
        column.codec.sqlType == 'decimal' &&
        column.decimalPrecision != null
    ? 'NUMERIC(${column.decimalPrecision},${column.decimalScale ?? 0})'
    : dialect == SqlDialect.postgres && column.codec.sqlType == 'integer'
    ? switch (column.integerBits ?? 64) {
        16 => 'SMALLINT',
        32 => 'INTEGER',
        _ => 'BIGINT',
      }
    : _storageType(column.codec.sqlType, dialect);

bool _sameStorage(Column<Object?> a, Column<Object?> b) =>
    a.codec.sqlType == b.codec.sqlType &&
    (a.integerBits ?? 64) == (b.integerBits ?? 64) &&
    a.decimalPrecision == b.decimalPrecision &&
    (a.decimalScale ?? 0) == (b.decimalScale ?? 0);

String _coerceColumn(
  String expression,
  Column<Object?> column,
  SqlDialect dialect,
) => dialect == SqlDialect.sqlite && column.decimalPrecision != null
    ? 'orm_decimal_cast_v1($expression, ${column.decimalPrecision}, ${column.decimalScale ?? 0})'
    : expression;

String _decimalCheck(String name, int precision, int scale) =>
    '${_quote(name)} IS NULL OR orm_decimal_fits_v1(${_quote(name)}, $precision, $scale)';

String _integerCheck(String name, int bits) {
  final column = _quote(name), max = bits == 16 ? 32767 : 2147483647;
  return "$column IS NULL OR (typeof($column) = 'integer' AND $column BETWEEN ${-max - 1} AND $max)";
}

/// Actual catalog columns, rather than a claimed migration version.
final class ColumnInfo {
  final String name;
  final String storageType;
  final bool nullable;
  final String? defaultSql;
  final bool generated;
  final int? integerBits;
  final String? collation;
  final int? decimalPrecision;
  final int? decimalScale;
  const ColumnInfo({
    required this.name,
    required this.storageType,
    required this.nullable,
    this.defaultSql,
    this.generated = false,
    this.integerBits,
    this.collation,
    this.decimalPrecision,
    this.decimalScale,
  });

  /// Removes the managed SQLite default coercion when drafting a declaration.
  String? get declarationDefaultSql =>
      defaultSql != null && storageType == 'TEXT' && decimalPrecision != null
      ? _uncoerceDecimalDefault(
              _normalizeDefault(defaultSql)!,
              decimalPrecision!,
              decimalScale ?? 0,
            ) ??
            defaultSql
      : defaultSql;
}

Future<List<ColumnInfo>> inspectColumns(
  Database<Backend> db,
  String table,
) async {
  if (db.dialect == SqlDialect.sqlite) {
    final rows = await db.execute(
      SqlCommand('PRAGMA table_xinfo(${_quote(table)})'),
    );
    final indexes = await db.execute(
      SqlCommand('PRAGMA index_list(${_quote(table)})'),
    );
    final rowidPrimaryKey = !indexes.rows.any((r) => r[3] == 'pk');
    final ddl = await db.execute(
      SqlCommand(
        "SELECT sql FROM main.sqlite_schema WHERE type = 'table' AND name = ?1",
        [table],
      ),
    );
    final sql = ddl.rows.firstOrNull?.first as String? ?? '';
    final checks = _sqliteChecks(sql);
    final collations = {
      for (final c in _sqliteColumnCollations(sql))
        _sqliteName(c.column): c.collation,
    };
    final columns = <ColumnInfo>[];
    for (final row in rows.rows) {
      final name = row[1] as String;
      final type = (row[2] as String).toUpperCase();
      final collation = collations[_sqliteName(name)] ?? 'BINARY';
      final digits =
          type == 'TEXT' && collation.toLowerCase() == 'orm_decimal_v1'
          ? _sqliteDecimalDigits(name, checks)
          : null;
      columns.add(
        ColumnInfo(
          name: name,
          storageType: type,
          collation: collation,
          decimalPrecision: digits?.$1,
          decimalScale: digits?.$2,
          nullable: row[3] == 0 && !(row[5] != 0 && rowidPrimaryKey),
          defaultSql: row[4] as String?,
          generated: (row[6] as int) > 0,
          integerBits: type == 'INTEGER'
              ? _sqliteIntegerBits(name, checks)
              : null,
        ),
      );
    }
    return columns;
  }

  final result = await db.execute(
    SqlCommand(
      '''
SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod),
       NOT a.attnotnull, pg_get_expr(d.adbin, d.adrelid),
       a.attidentity <> '' OR a.attgenerated <> ''
FROM pg_catalog.pg_attribute a
JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE c.relname = \$1 AND n.nspname = current_schema() AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum''',
      [table],
    ),
  );
  return [
    for (final row in result.rows)
      ColumnInfo(
        name: row[0] as String,
        storageType: (row[1] as String).toUpperCase().replaceAll(
          'TIMESTAMP WITH TIME ZONE',
          'TIMESTAMPTZ',
        ),
        nullable: row[2] as bool,
        defaultSql: row[3] as String?,
        generated: row[4] as bool,
        decimalPrecision: _postgresDecimalDigits(row[1] as String)?.$1,
        decimalScale: _postgresDecimalDigits(row[1] as String)?.$2,
        integerBits: switch ((row[1] as String).toUpperCase()) {
          'SMALLINT' => 16,
          'INTEGER' => 32,
          'BIGINT' => 64,
          _ => null,
        },
      ),
  ];
}

/// Column drift check. Constraints, indexes and unmanaged objects are separate
/// catalog checks; this method does not pretend that columns prove full equality.
Future<List<String>> verifyColumns(
  Database<Backend> db,
  List<TableSchema> tables,
) async {
  final differences = <String>[];
  for (final table in tables) {
    final actual = {
      for (final c in await inspectColumns(db, table.name)) c.name: c,
    };
    for (final expected in table.columns) {
      final column = actual.remove(expected.name);
      final path = '${table.name}.${expected.name}';
      if (column == null) {
        differences.add('$path is missing');
        continue;
      }
      if (column.storageType != _columnStorageType(expected, db.dialect)) {
        differences.add('$path type is ${column.storageType}');
      }
      if (column.nullable != expected.nullable) {
        differences.add('$path nullability differs');
      }
      if (!_matchesDecimalDigits(expected, column)) {
        differences.add('$path decimal precision/scale differs');
      }
      if (db.dialect == SqlDialect.sqlite &&
          !_matchesCollation(expected, column)) {
        differences.add('$path collation differs');
      }
      if (expected.codec.sqlType == 'integer' &&
          (column.integerBits ?? 64) != (expected.integerBits ?? 64)) {
        differences.add('$path integer width differs');
      }
    }
    for (final extra in actual.keys) {
      differences.add('${table.name}.$extra is unmanaged');
    }
  }
  return differences;
}

bool _matchesCollation(Column<Object?> expected, ColumnInfo actual) =>
    (actual.collation ?? 'BINARY').toLowerCase() ==
    (expected.codec.sqlType == 'decimal' ? 'orm_decimal_v1' : 'binary');

bool _matchesDecimalDigits(Column<Object?> expected, ColumnInfo actual) =>
    expected.decimalPrecision == actual.decimalPrecision &&
    (expected.decimalScale ?? 0) == (actual.decimalScale ?? 0);

(int, int)? _postgresDecimalDigits(String type) {
  final match = RegExp(
    r'^numeric\((\d+),(-?\d+)\)$',
    caseSensitive: false,
  ).firstMatch(type.replaceAll(' ', ''));
  return match == null ? null : (int.parse(match[1]!), int.parse(match[2]!));
}
