import 'dart:convert';
import 'dart:io';

import 'package:orm/generate.dart';
import 'package:orm/migrate.dart';
import 'package:orm/postgres.dart';
import 'package:orm/sqlite.dart';
import 'package:test/test.dart';

void main() {
  for (final backend in [
    'sqlite',
    if (Platform.environment.containsKey('ORM_TEST_POSTGRES')) 'postgres',
  ]) {
    group('catalog import $backend', () {
      late Database<Backend> db;
      late Directory directory;
      setUp(() async {
        directory = await Directory('.dart_tool/orm-import-tests/$backend')
            .create(recursive: true);
        if (backend == 'sqlite') {
          db = await sqlite(
            SqliteOptions.file('${directory.path}/data.sqlite'),
          );
        } else {
          db = postgres(
            PostgresOptions(
              url: Uri.parse(Platform.environment['ORM_TEST_POSTGRES']!),
              tls: .disable,
              schema: 'orm_import_tests',
            ),
          );
          await db.execute(
            SqlCommand('DROP SCHEMA IF EXISTS orm_import_tests CASCADE'),
          );
          await db.execute(SqlCommand('CREATE SCHEMA orm_import_tests'));
        }
      });
      tearDown(() async {
        await db.close();
        await directory.delete(recursive: true);
      });
      String getInt() => backend == 'sqlite' ? 'INTEGER' : 'BIGINT';
      Future<GeneratedSchema> generate(ImportedSchema draft) async {
        final source = '${directory.path}/schema.dart';
        await File(source).writeAsString(draft.dart);
        final result = await generateSchema(source);
        await File('${directory.path}/schema.orm.dart')
            .writeAsString(result.dart);
        return result;
      }

      test('imports records, identities, defaults and constraints then baselines unchanged rows', () async {
        final integer = getInt();
        await db.execute(
          SqlCommand(
            'CREATE TABLE accounts (id $integer ${backend == 'postgres' ? 'GENERATED BY DEFAULT AS IDENTITY' : ''} PRIMARY KEY NOT NULL, email TEXT NOT NULL UNIQUE, label TEXT, score $integer NOT NULL DEFAULT 0)',
          ),
        );
        await db.execute(
          SqlCommand(
            'CREATE TABLE notes (id $integer PRIMARY KEY NOT NULL, account_id $integer NOT NULL DEFAULT 1, body TEXT NOT NULL, FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET DEFAULT)',
          ),
        );
        await db.execute(SqlCommand('CREATE INDEX notes_body ON notes(body)'));
        await db.execute(
          SqlCommand("INSERT INTO accounts(email) VALUES ('existing')"),
        );
        await db.execute(
          SqlCommand(
            "INSERT INTO notes(id, account_id, body) VALUES (7, 1, 'kept')",
          ),
        );
        final draft = await importSchema(db);
        expect(draft.issues, isEmpty);
        expect(draft.entities, {'accounts': 'accounts', 'notes': 'notes'});
        expect(draft.dart, contains('@Id.generated()'));
        final client = await generate(draft);
        final snapshot = SchemaSnapshot.fromJson(client.snapshot);
        expect((await verifySchema(db, snapshot)).differences, isEmpty);
        final history = [Migration.create('0001_baseline', snapshot.tables)];
        await Migrator(db).baseline(history, expected: snapshot);
        expect(
          (await db.execute(SqlCommand('SELECT email FROM accounts'))).rows,
          [
            ['existing'],
          ],
        );
        expect((await db.execute(SqlCommand('SELECT body FROM notes'))).rows, [
          ['kept'],
        ]);
        expect((await importSchema(db)).entities, draft.entities);
        final connection = backend == 'sqlite'
            ? 'await sqlite(SqliteOptions.file(${jsonEncode('${directory.absolute.path}/data.sqlite')}))'
            : "postgres(PostgresOptions(url: Uri.parse(Platform.environment['ORM_TEST_POSTGRES']!), tls: .disable, schema: 'orm_import_tests'))";
        await File('${directory.path}/use.dart').writeAsString(
          '''
import 'dart:io';
import 'package:orm/$backend.dart';
import 'schema.orm.dart';
Future<void> main() async {
  final db = $connection;
  try {
    final account = await db.accounts.create(email: 'created');
    final note = await db.notes.create(id: const Change.set(8), accountId: Change.set(account.id), body: 'new');
    final joined = await db.notes.byId(note.id).select((n) => (n.body, n.notesAccounts.select((a) => a.email).required()).map((body, email) => (body: body, email: email))).single();
    if (joined != (body: 'new', email: 'created')) throw StateError('Typed relation lost values');
    await db.accounts.byId(account.id).delete().execute();
    final remaining = await db.notes.byId(note.id).single();
    if (remaining.accountId != 1) throw StateError('SET DEFAULT was not preserved');
    print('Imported typed client preserves rows, defaults and relations.');
  } finally { await db.close(); }
}
'''
              .replaceAll(
                "import 'dart:io';",
                backend == 'sqlite' ? '' : "import 'dart:io';",
              )
              .replaceAll(
                'id: const Change.set(8)',
                backend == 'sqlite' ? 'id: const Change.set(8)' : 'id: 8',
              ),
        );
        final analysis = await Process.run(Platform.resolvedExecutable, [
          'analyze',
          '${directory.path}/use.dart',
          '${directory.path}/schema.orm.dart',
        ]);
        expect(
          analysis.exitCode,
          0,
          reason: '${analysis.stdout}\n${analysis.stderr}',
        );
        if (backend == 'sqlite') {
          final compiled = await Process.run(Platform.resolvedExecutable, [
            'compile',
            'exe',
            '${directory.path}/use.dart',
            '-o',
            '${directory.path}/use',
          ]);
          expect(
            compiled.exitCode,
            0,
            reason: '${compiled.stdout}\n${compiled.stderr}',
          );
        }
        final run = backend == 'sqlite'
            ? await Process.run('${directory.path}/use', const <String>[])
            : await Process.run(Platform.resolvedExecutable, [
                'run',
                '${directory.path}/use.dart',
              ]);
        expect(run.exitCode, 0, reason: '${run.stdout}\n${run.stderr}');
      }, timeout: const Timeout(Duration(minutes: 2)));

      test('normalizes reserved, colliding and hostile identifiers without changing physical names', () async {
        final integer = getInt();
        String quote(String s) => '"${s.replaceAll('"', '""')}"';
        final names = [
          r'user-$name',
          'user name',
          'class',
          '123',
          '中文',
          'execute',
          'users_schema',
        ];
        final columns = [
          'id',
          'table',
          'column',
          'class',
          'hashCode',
          'runtimeType',
          'a b',
          'a-b',
          '中文',
          r'value$1',
          'line\nbreak',
          'quote"name',
          'row',
        ];
        for (final name in names) {
          await db.execute(
            SqlCommand(
              'CREATE TABLE ${quote(name)} (${[for (final c in columns) '${quote(c)} $integer NOT NULL'].join(', ')}, PRIMARY KEY (id))',
            ),
          );
        }
        await db.execute(
          SqlCommand('CREATE TABLE foo (bar_baz $integer NOT NULL)'),
        );
        await db.execute(
          SqlCommand('CREATE TABLE foo_bar (baz $integer NOT NULL)'),
        );
        final draft = await importSchema(db);
        expect(draft.issues, isEmpty);
        expect(draft.entities.values.toSet().length, names.length + 2);
        for (final name in names) {
          expect(draft.fields[name]!.values.toSet().length, columns.length);
        }
        final client = await generate(draft);
        expect(
          (await verifySchema(
            db,
            SchemaSnapshot.fromJson(client.snapshot),
          )).differences,
          isEmpty,
        );
        final analysis = await Process.run(Platform.resolvedExecutable, [
          'analyze',
          '${directory.path}/schema.dart',
          '${directory.path}/schema.orm.dart',
        ]);
        expect(
          analysis.exitCode,
          0,
          reason: '${analysis.stdout}\n${analysis.stderr}',
        );
        expect((await importSchema(db)).dart, draft.dart);
      });

      test('composite and self relations preserve key order and unique indexes', () async {
        final integer = getInt();
        await db.execute(
          SqlCommand(
            'CREATE TABLE owners (tenant $integer NOT NULL, id $integer NOT NULL, parent_tenant $integer, parent_id $integer, PRIMARY KEY(tenant, id), FOREIGN KEY(parent_tenant, parent_id) REFERENCES owners(tenant, id) ON DELETE SET NULL)',
          ),
        );
        await db.execute(
          SqlCommand(
            'CREATE TABLE labels (tenant $integer NOT NULL, name TEXT NOT NULL)',
          ),
        );
        await db.execute(
          SqlCommand('CREATE UNIQUE INDEX label_key ON labels(tenant, name)'),
        );
        await db.execute(
          SqlCommand(
            'CREATE TABLE links (tenant $integer NOT NULL, label TEXT NOT NULL, FOREIGN KEY(tenant, label) REFERENCES labels(tenant, name))',
          ),
        );
        final draft = await importSchema(db);
        expect(draft.issues, isEmpty);
        final result = await generate(draft);
        expect(
          (await verifySchema(
            db,
            SchemaSnapshot.fromJson(result.snapshot),
          )).differences,
          isEmpty,
        );
        final subset = await importSchema(db, tables: ['links']);
        expect(subset.hasBlockingIssues, true);
        expect(subset.issues.single.code, 'IMPORT.RELATION');
        await generate(subset);
      });

      test('unsupported storage excludes its table while computed SQL imports with a review note', () async {
        final integer = getInt();
        await db.execute(
          SqlCommand(
            'CREATE TABLE supported (id $integer NOT NULL PRIMARY KEY)',
          ),
        );
        await db.execute(
          SqlCommand('CREATE TABLE unsupported (amount VARCHAR(12) NOT NULL)'),
        );
        await db.execute(
          SqlCommand(
            'CREATE TABLE computed (id $integer NOT NULL PRIMARY KEY, doubled $integer GENERATED ALWAYS AS (id * 2) STORED)',
          ),
        );
        final draft = await importSchema(db);
        expect(draft.entities.keys, ['computed', 'supported']);
        expect(
          draft.issues.map((i) => i.code),
          containsAll(['IMPORT.TYPE', 'IMPORT.COMPUTED_SQL']),
        );
        expect(draft.hasBlockingIssues, true);
        await generate(draft);
        expect(
          (await importSchema(db, tables: ['missing'])).issues.single.code,
          'IMPORT.MISSING',
        );
      });

      test('read-only snapshot and selected scope reject temporary shadowing and active transactions', () async {
        final integer = getInt();
        await db.execute(
          SqlCommand('CREATE TABLE stored (id $integer NOT NULL PRIMARY KEY)'),
        );
        await db.session((session) async {
          await session.execute(
            SqlCommand('CREATE TEMP TABLE stored (wrong TEXT)'),
          );
          try {
            final draft = await importSchema(session, tables: ['stored']);
            expect(draft.issues.single.code, 'IMPORT.SCOPE');
            expect(draft.entities, isEmpty);
          } finally {
            await session.execute(
              SqlCommand(
                'DROP TABLE ${backend == 'sqlite' ? 'temp' : 'pg_temp'}.stored',
              ),
            );
          }
          await session.transaction((tx) async {
            expect(() => importSchema(tx), throwsA(isA<OrmException>()));
          });
        });
        expect(() => importSchema(db, tables: []), throwsArgumentError);
        expect(
          () => importSchema(db, tables: ['stored', 'stored']),
          throwsArgumentError,
        );
        if (backend == 'sqlite') {
          final readOnly = await sqlite(
            SqliteOptions.readOnly('${directory.path}/data.sqlite'),
          );
          try {
            expect((await importSchema(readOnly)).entities.keys, ['stored']);
          } finally {
            await readOnly.close();
          }
        }
      });

      test(
        'physical storage mapping does not infer domain types from data',
        () async {
          if (backend == 'sqlite') {
            await db.execute(
              SqlCommand(
                'CREATE TABLE values_table (id INTEGER NOT NULL PRIMARY KEY, document TEXT, timestamp TEXT, flag INTEGER NOT NULL, data BLOB, score REAL)',
              ),
            );
            final draft = await importSchema(db);
            expect(draft.dart, contains('String? document'));
            expect(draft.dart, contains('String? timestamp'));
            expect(draft.dart, contains('int flag'));
            await generate(draft);
          } else {
            await db.execute(
              SqlCommand(
                'CREATE TABLE values_table (id BIGINT NOT NULL PRIMARY KEY, document JSONB, timestamp TIMESTAMPTZ, flag BOOLEAN NOT NULL, data BYTEA, score DOUBLE PRECISION)',
              ),
            );
            final draft = await importSchema(db);
            expect(draft.dart, contains('@UseCodec(Codecs.jsonDocument)'));
            expect(draft.dart, contains('SqlJson? document'));
            final result = await generate(draft);
            expect(
              (await verifySchema(
                db,
                SchemaSnapshot.fromJson(result.snapshot),
              )).differences,
              isEmpty,
            );
          }
        },
      );

      test('views triggers and specialized indexes remain in the review report', () async {
        final integer = getInt();
        await db.execute(
          SqlCommand(
            'CREATE TABLE records (id $integer NOT NULL PRIMARY KEY, label TEXT)',
          ),
        );
        await db.execute(
          SqlCommand(
            'CREATE INDEX label_partial ON records(label) WHERE label IS NOT NULL',
          ),
        );
        await db.execute(
          SqlCommand('CREATE VIEW labels AS SELECT label FROM records'),
        );
        if (backend == 'sqlite') {
          await db.execute(
            SqlCommand('''
CREATE TRIGGER label_normalize AFTER INSERT ON records BEGIN
  UPDATE records SET label = upper(NEW.label) WHERE id = NEW.id;
END'''),
          );
        } else {
          await db.execute(
            SqlCommand(r'''
CREATE FUNCTION normalize_label() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.label := upper(NEW.label); RETURN NEW; END $$'''),
          );
          await db.execute(
            SqlCommand('''
CREATE TRIGGER label_normalize BEFORE INSERT ON records
FOR EACH ROW EXECUTE FUNCTION normalize_label()'''),
          );
        }
        if (backend == 'postgres') {
          await db.execute(
            SqlCommand(
              'CREATE INDEX label_pattern ON records(label text_pattern_ops)',
            ),
          );
          await db.execute(
            SqlCommand(
              'CREATE INDEX label_collation ON records(label COLLATE "C")',
            ),
          );
          await db.execute(
            SqlCommand(
              'CREATE UNIQUE INDEX label_nulls ON records(label) NULLS NOT DISTINCT',
            ),
          );
          await db.execute(
            SqlCommand(
              'ALTER TABLE records ADD CONSTRAINT label_unique UNIQUE NULLS NOT DISTINCT(label)',
            ),
          );
        }
        final draft = await importSchema(db);
        expect(draft.entities.keys, ['records']);
        expect(
          draft.issues.any((i) => i.object.contains('label_partial')),
          true,
        );
        expect(draft.issues.any((i) => i.object.contains('labels')), true);
        expect(
          draft.issues.any((i) => i.object.contains('label_normalize')),
          true,
        );
        expect(draft.hasBlockingIssues, false);
        if (backend == 'postgres') {
          for (final name in [
            'label_pattern',
            'label_collation',
            'label_nulls',
            'label_unique',
          ]) {
            expect(
              draft.issues.any((i) => i.object.contains(name)),
              true,
              reason: name,
            );
          }
        }
        final result = await generate(draft);
        expect(
          (await verifySchema(
            db,
            SchemaSnapshot.fromJson(result.snapshot),
          )).differences,
          isEmpty,
        );
        // Read-only import and verification must leave the trigger operational.
        await db.execute(
          SqlCommand(
            backend == 'sqlite'
                ? 'INSERT INTO records(id, label) VALUES (?1, ?2)'
                : r'INSERT INTO records(id, label) VALUES ($1, $2)',
            [1, 'kept'],
          ),
        );
        expect(
          (await db.execute(
            SqlCommand('SELECT label FROM records WHERE id = 1'),
          )).rows.single.single,
          'KEPT',
        );
      });

      if (backend == 'sqlite') {
        test('nullable primary keys, virtual tables and their storage tables need explicit handling', () async {
          await db.execute(
            SqlCommand('CREATE TABLE nullable_key (id TEXT PRIMARY KEY)'),
          );
          await db.execute(
            SqlCommand('CREATE VIRTUAL TABLE search USING fts5(body)'),
          );
          final draft = await importSchema(db);
          expect(draft.entities, isEmpty);
          expect(
            draft.issues.any((i) => i.code == 'IMPORT.NULLABLE_KEY'),
            true,
          );
          expect(
            draft.issues.any((i) => i.object == 'search' && i.blocking),
            true,
          );
          expect(draft.issues.any((i) => i.object == 'search_data'), true);
        });
        test(
          'foreign keys with coercible but different Dart types are reported',
          () async {
            await db.execute(
              SqlCommand('CREATE TABLE parent (id TEXT NOT NULL PRIMARY KEY)'),
            );
            await db.execute(
              SqlCommand(
                'CREATE TABLE child (parent_id INTEGER REFERENCES parent(id))',
              ),
            );
            final draft = await importSchema(db);
            expect(draft.issues.single.code, 'IMPORT.RELATION');
            await generate(draft);
          },
        );
      } else {
        test(
          'policy reports retain roles, commands, mode and row-security state',
          () async {
            await db.execute(
              SqlCommand(
                'CREATE TABLE protected (id BIGINT NOT NULL PRIMARY KEY)',
              ),
            );
            await db.execute(
              SqlCommand('''
CREATE POLICY positive ON protected AS RESTRICTIVE FOR ALL TO PUBLIC
USING (id > 0) WITH CHECK (id < 100)'''),
            );
            Future<Map<String, Object?>> security() async {
              final table = await inspectTable(db, 'protected');
              final policy = jsonDecode(
                table.unmanaged
                    .singleWhere((o) => o.kind == 'policy')
                    .definition,
              ) as Map<String, Object?>;
              expect(policy, {
                'permissive': 'RESTRICTIVE',
                'roles': ['public'],
                'command': 'ALL',
                'using': '(id > 0)',
                'withCheck': '(id < 100)',
              });
              return jsonDecode(
                table.unmanaged
                    .singleWhere((o) => o.kind == 'row_security')
                    .definition,
              ) as Map<String, Object?>;
            }

            expect(await security(), {'enabled': false, 'forced': false});
            await db.execute(
              SqlCommand('ALTER TABLE protected ENABLE ROW LEVEL SECURITY'),
            );
            await db.execute(
              SqlCommand('ALTER TABLE protected FORCE ROW LEVEL SECURITY'),
            );
            expect(await security(), {'enabled': true, 'forced': true});
            final draft = await importSchema(db);
            expect(draft.hasBlockingIssues, false);
            expect(
              draft.issues.where((i) => i.object.contains('protected')),
              hasLength(2),
            );
            final generated = await generate(draft);
            final expected = SchemaSnapshot.fromJson(generated.snapshot);
            final baseline = await Migrator(db).baseline([
              Migration.create('0001_protected', expected.tables),
            ], expected: expected);
            expect(baseline.matches, true);
            expect(
              baseline.unmanaged.map((o) => o.kind),
              containsAll(['policy', 'row_security']),
            );
            expect(await security(), {'enabled': true, 'forced': true});
            await db.execute(
              SqlCommand('ALTER TABLE protected DISABLE ROW LEVEL SECURITY'),
            );
            expect(await security(), {'enabled': false, 'forced': true});
            await db.execute(
              SqlCommand('ALTER TABLE protected NO FORCE ROW LEVEL SECURITY'),
            );
            await db.execute(SqlCommand('DROP POLICY positive ON protected'));
            expect((await inspectTable(db, 'protected')).unmanaged, isEmpty);
          },
        );

        test('always identity and inherited tables are not flattened into ordinary writable models', () async {
          await db.execute(
            SqlCommand(
              'CREATE TABLE always_id (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY)',
            ),
          );
          await db.execute(
            SqlCommand('CREATE TABLE ancestor (id BIGINT PRIMARY KEY)'),
          );
          await db.execute(
            SqlCommand('CREATE TABLE descendant () INHERITS (ancestor)'),
          );
          final draft = await importSchema(db);
          expect(draft.entities, isEmpty);
          expect(draft.issues.any((i) => i.code == 'IMPORT.GENERATED'), true);
          expect(
            draft.issues.where((i) => i.code == 'IMPORT.SCOPE'),
            hasLength(2),
          );
        });
      }
    });
  }
}
