// GENERATED CODE - DO NOT MODIFY BY HAND.
// Frozen physical schema. Independent of current application models.
import 'package:orm/database.dart';
import 'package:orm/schema.dart';

/// Reviewed schema state for this database engine.
const frozenSchema = SchemaSnapshot(
  engine: Engine.sqlite,
  tables: [
    TableDefinition("users", [
      ColumnDefinition(
        name: "id",
        field: "id",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: true,
        identity: true,
        unique: false,
      ),
      ColumnDefinition(
        name: "username",
        field: "username",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: true,
      ),
      ColumnDefinition(
        name: "age",
        field: "age",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "nickname",
        field: "nickname",
        type: ScalarType.text,
        nullable: true,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "active",
        field: "active",
        type: ScalarType.boolean,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        defaultValue: true,
      ),
      ColumnDefinition(
        name: "score",
        field: "score",
        type: ScalarType.real,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        defaultValue: 0.0,
      ),
      ColumnDefinition(
        name: "joined_at",
        field: "joinedAt",
        type: ScalarType.dateTime,
        nullable: true,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "avatar",
        field: "avatar",
        type: ScalarType.bytes,
        nullable: true,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
    ]),
    TableDefinition("posts", [
      ColumnDefinition(
        name: "id",
        field: "id",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: true,
        identity: true,
        unique: false,
      ),
      ColumnDefinition(
        name: "author_id",
        field: "authorId",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        references: ForeignKey("users", "id", onDelete: "cascade"),
      ),
      ColumnDefinition(
        name: "title",
        field: "title",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "body",
        field: "body",
        type: ScalarType.text,
        nullable: true,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
    ]),
    TableDefinition("products", [
      ColumnDefinition(
        name: "id",
        field: "id",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: true,
        identity: true,
        unique: false,
      ),
      ColumnDefinition(
        name: "sku",
        field: "sku",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: true,
      ),
      ColumnDefinition(
        name: "name",
        field: "name",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "price_cents",
        field: "priceCents",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "stock",
        field: "stock",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        defaultValue: 0,
      ),
    ]),
    TableDefinition("orders", [
      ColumnDefinition(
        name: "id",
        field: "id",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: true,
        identity: true,
        unique: false,
      ),
      ColumnDefinition(
        name: "user_id",
        field: "userId",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        references: ForeignKey("users", "id", onDelete: "restrict"),
      ),
      ColumnDefinition(
        name: "request_key",
        field: "requestKey",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: true,
      ),
      ColumnDefinition(
        name: "request_signature",
        field: "requestSignature",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "total_cents",
        field: "totalCents",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        defaultValue: 0,
      ),
      ColumnDefinition(
        name: "status",
        field: "status",
        type: ScalarType.text,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        defaultValue: "building",
      ),
      ColumnDefinition(
        name: "created_at",
        field: "createdAt",
        type: ScalarType.dateTime,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
    ]),
    TableDefinition("order_lines", [
      ColumnDefinition(
        name: "id",
        field: "id",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: true,
        identity: true,
        unique: false,
      ),
      ColumnDefinition(
        name: "order_id",
        field: "orderId",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        references: ForeignKey("orders", "id", onDelete: "cascade"),
      ),
      ColumnDefinition(
        name: "product_id",
        field: "productId",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
        references: ForeignKey("products", "id", onDelete: "restrict"),
      ),
      ColumnDefinition(
        name: "quantity",
        field: "quantity",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
      ColumnDefinition(
        name: "unit_price_cents",
        field: "unitPriceCents",
        type: ScalarType.integer,
        nullable: false,
        primaryKey: false,
        identity: false,
        unique: false,
      ),
    ]),
  ],
);
