builders:
  orm:
    import: "package:orm/builder.dart"
    builder_factories: ["ormBuilder"]
    build_extensions:
      ".dart": [".orm.dart", ".orm.json"]
    auto_apply: none
    build_to: source
  queries:
    import: "package:orm/builder.dart"
    builder_factories: ["ormQueryBuilder"]
    build_extensions:
      ".dart": [".queries.dart", ".queries.json"]
    auto_apply: none
    build_to: source
