name: orm
description: Typed relational data access for Dart, from declaration to migration.
version: 6.0.0-beta.11
repository: https://github.com/medz/dart-orm
issue_tracker: https://github.com/medz/dart-orm/issues
documentation: https://github.com/medz/dart-orm/tree/main/doc
topics:
  - orm
  - database
  - sqlite
  - postgresql
environment:
  sdk: '>=3.13.0 <4.0.0'
dependencies:
  analyzer: ^14.1.0
  crypto: ^3.0.7
  dart_style: ^3.1.13
  path: ^1.9.1
  postgres: ^3.5.20
  sqlite3: ^3.6.0
dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
executables:
  orm:
