// Review before applying. Applied migrations must remain unchanged.
import 'package:orm/orm.dart';
import 'package:orm/migrate.dart';

const migrationChecksum =
    "9eb9f65f653238489d3121876d1f13b23d3d27492259ec995c4fef43a29bee14";
final migration = Migration.steps("0001_initial", {
  SqlDialect.sqlite: [
    ExecuteSql(
      "CREATE TABLE \"users\" (\"id\" INTEGER PRIMARY KEY NOT NULL, \"email\" TEXT NOT NULL, \"nickname\" TEXT, \"score\" INTEGER NOT NULL DEFAULT (0), UNIQUE (\"email\"))",
    ),
    ExecuteSql(
      "CREATE TABLE \"posts\" (\"id\" INTEGER PRIMARY KEY NOT NULL, \"author_id\" INTEGER NOT NULL, \"title\" TEXT NOT NULL, \"created_at\" TEXT COLLATE \"orm_instant_v1\" NOT NULL, FOREIGN KEY (\"author_id\") REFERENCES \"users\" (\"id\") ON DELETE CASCADE)",
    ),
    ExecuteSql(
      "CREATE INDEX \"author_timeline\" ON \"posts\" (\"author_id\", \"created_at\", \"id\")",
    ),
  ],
  SqlDialect.postgres: [
    ExecuteSql(
      "CREATE TABLE \"users\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, \"email\" TEXT NOT NULL, \"nickname\" TEXT, \"score\" BIGINT NOT NULL DEFAULT (0), PRIMARY KEY (\"id\"), UNIQUE (\"email\"))",
    ),
    ExecuteSql(
      "CREATE TABLE \"posts\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, \"author_id\" BIGINT NOT NULL, \"title\" TEXT NOT NULL, \"created_at\" TIMESTAMPTZ NOT NULL, PRIMARY KEY (\"id\"))",
    ),
    ExecuteSql(
      "ALTER TABLE \"posts\" ADD FOREIGN KEY (\"author_id\") REFERENCES \"users\" (\"id\") ON DELETE CASCADE",
    ),
    ExecuteSql(
      "CREATE INDEX \"author_timeline\" ON \"posts\" (\"author_id\", \"created_at\", \"id\")",
    ),
  ],
}, snapshot: _schema);

final _schema = SchemaSnapshot([
  TableSchema(
    "users",
    columns: [
      Column("id", Codecs.integer, generated: true),
      Column("email", Codecs.text),
      Column("nickname", Codecs.text.nullable(), nullable: true),
      Column("score", Codecs.integer, defaultSql: "0"),
    ],
    primaryKey: ["id"],
    uniqueKeys: [
      ["email"],
    ],
  ),
  TableSchema(
    "posts",
    columns: [
      Column("id", Codecs.integer, generated: true),
      Column("author_id", Codecs.integer),
      Column("title", Codecs.text),
      Column("created_at", Codecs.dateTime),
    ],
    primaryKey: ["id"],

    indexes: [
      IndexSchema("author_timeline", [
        "author_id",
        "created_at",
        "id",
      ], unique: false),
    ],
    foreignKeys: [
      ForeignKey(["author_id"], "users", ["id"], onDelete: "CASCADE"),
    ],
  ),
]);
