// Review before applying. Applied migrations must remain unchanged.
import 'package:orm/orm.dart';
import 'package:orm/migrate.dart';

const migrationChecksum =
    "a5d45b89caaf4503d516f6b43138c4fd40e6ca88114f88ac1c3997af1afef421";
final migration = Migration.steps("0001_initial", {
  SqlDialect.sqlite: [
    ExecuteSql(
      "CREATE TABLE \"notes\" (\"id\" INTEGER PRIMARY KEY NOT NULL, \"body\" TEXT NOT NULL, \"created_at\" TEXT COLLATE \"orm_instant_v1\" NOT NULL)",
    ),
  ],
  SqlDialect.postgres: [
    ExecuteSql(
      "CREATE TABLE \"notes\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, \"body\" TEXT NOT NULL, \"created_at\" TIMESTAMPTZ NOT NULL, PRIMARY KEY (\"id\"))",
    ),
  ],
}, snapshot: _schema);

final _schema = SchemaSnapshot([
  TableSchema(
    "notes",
    columns: [
      Column("id", Codecs.integer, generated: true),
      Column("body", Codecs.text),
      Column("created_at", Codecs.dateTime),
    ],
    primaryKey: ["id"],
  ),
]);
