// Review before applying. Applied migrations must remain unchanged.
import 'package:orm/orm.dart';
import 'package:orm/migrate.dart';

const migrationChecksum =
    "089cd5d7ab42fa7491b8e46ca3b00899b34f926983f6a93f2812cf1b0c9afb92";
final migration = Migration.steps(
  "0002_comments",
  {
    SqlDialect.sqlite: [
      ExecuteSql(
        "CREATE TABLE \"comments\" (\"id\" INTEGER PRIMARY KEY NOT NULL, \"note_id\" INTEGER NOT NULL, \"text\" TEXT NOT NULL, FOREIGN KEY (\"note_id\") REFERENCES \"notes\" (\"id\") ON DELETE CASCADE)",
      ),
      ExecuteSql(
        "ALTER TABLE \"notes\" ADD COLUMN \"done\" INTEGER NOT NULL DEFAULT (false)",
      ),
    ],
    SqlDialect.postgres: [
      ExecuteSql(
        "CREATE TABLE \"comments\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, \"note_id\" BIGINT NOT NULL, \"text\" TEXT NOT NULL, PRIMARY KEY (\"id\"))",
      ),
      ExecuteSql(
        "ALTER TABLE \"notes\" ADD COLUMN \"done\" BOOLEAN NOT NULL DEFAULT (false)",
      ),
      ExecuteSql(
        "ALTER TABLE \"comments\" ADD FOREIGN KEY (\"note_id\") REFERENCES \"notes\" (\"id\") ON DELETE CASCADE",
      ),
    ],
  },
  previous: "a5d45b89caaf4503d516f6b43138c4fd40e6ca88114f88ac1c3997af1afef421",
  snapshot: _schema,
);

final _schema = SchemaSnapshot([
  TableSchema(
    "notes",
    columns: [
      Column("id", Codecs.integer, generated: true),
      Column("body", Codecs.text),
      Column("done", Codecs.boolean, defaultSql: "false"),
      Column("created_at", Codecs.dateTime),
    ],
    primaryKey: ["id"],
  ),
  TableSchema(
    "comments",
    columns: [
      Column("id", Codecs.integer, generated: true),
      Column("note_id", Codecs.integer),
      Column("text", Codecs.text),
    ],
    primaryKey: ["id"],

    foreignKeys: [
      ForeignKey(["note_id"], "notes", ["id"], onDelete: "CASCADE"),
    ],
  ),
]);
