import 'package:orm/orm.dart';

typedef User = ({int id, String email, String? nickname, int score});

final userId = Column('id', Codecs.integer, generated: true);
final userEmail = Column('email', Codecs.text);
final userNickname = Column('nickname', Codecs.text.nullable(), nullable: true);
final userScore = Column('score', Codecs.integer, defaultSql: '0');
final usersSchema = TableSchema(
  'users',
  columns: [userId, userEmail, userNickname, userScore],
  primaryKey: ['id'],
  uniqueKeys: [
    ['email'],
  ],
);

final class UserFields extends Fields {
  late final id = column(userId);
  late final email = column(userEmail);
  late final nickname = column(userNickname);
  late final score = column(userScore);
  UserFields(super.table);
  Relation<Post, PostFields> get posts =>
      Relation(postsTable, parent: [id], child: (p) => [p.authorId]);
}

typedef Post = ({int id, int authorId, String title, String? tag});
final postId = Column('id', Codecs.integer, generated: true);
final postAuthorId = Column('author_id', Codecs.integer);
final postTitle = Column('title', Codecs.text);
final postTag = Column('tag', Codecs.text.nullable(), nullable: true);
final postsSchema = TableSchema(
  'posts',
  columns: [postId, postAuthorId, postTitle, postTag],
  primaryKey: ['id'],
  foreignKeys: [
    const ForeignKey(['author_id'], 'users', ['id']),
  ],
);

final class PostFields extends Fields {
  late final id = column(postId);
  late final authorId = column(postAuthorId);
  late final title = column(postTitle);
  late final tag = column(postTag);
  PostFields(super.table);
  Relation<User, UserFields> get author =>
      Relation(users, parent: [authorId], child: (u) => [u.id]);
}

final postsTable = Table<Post, PostFields>(
  postsSchema,
  PostFields.new,
  (p) => (p.id, p.authorId, p.title, p.tag).map(
    (id, authorId, title, tag) =>
        (id: id, authorId: authorId, title: title, tag: tag),
  ),
);

final users = Table<User, UserFields>(
  usersSchema,
  UserFields.new,
  (u) => (u.id, u.email, u.nickname, u.score).map(
    (id, email, nickname, score) =>
        (id: id, email: email, nickname: nickname, score: score),
  ),
);

Future<void> createTables(Database<Backend> db) => db
    .execute(
      SqlCommand(
        'CREATE TABLE users (id ${db.dialect == SqlDialect.sqlite ? 'INTEGER PRIMARY KEY' : 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'}, '
        'email TEXT NOT NULL UNIQUE, nickname TEXT, score INTEGER NOT NULL DEFAULT 0)',
      ),
    )
    .then((_) {});
