import 'package:orm/orm.dart';

typedef User = ({int id, String email, String? nickname, int score});

final userId = Column('id', Codecs.integer, generated: true);
final userEmail = Column('email', Codecs.text);
final userNickname = Column('nickname', Codecs.text.nullable(), nullable: true);
final userScore = Column('score', Codecs.integer, defaultSql: '0');
final usersSchema = TableSchema(
  'users',
  columns: [userId, userEmail, userNickname, userScore],
  primaryKey: ['id'],
  uniqueKeys: [
    ['email'],
  ],
);

final class UserFields extends Fields {
  late final id = column(userId);
  late final email = column(userEmail);
  late final nickname = column(userNickname);
  late final score = column(userScore);
  UserFields(super.table);
}

final users = Table<User, UserFields>(
  usersSchema,
  UserFields.new,
  (u) => (u.id, u.email, u.nickname, u.score).map(
    (id, email, nickname, score) =>
        (id: id, email: email, nickname: nickname, score: score),
  ),
);

Future<void> createTables(Database<Backend> db) => db
    .execute(
      SqlCommand(
        'CREATE TABLE users (id ${db.dialect == SqlDialect.sqlite ? 'INTEGER PRIMARY KEY' : 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'}, '
        'email TEXT NOT NULL UNIQUE, nickname TEXT, score INTEGER NOT NULL DEFAULT 0)',
      ),
    )
    .then((_) {});
