// Generated by tool/build_sqlite_web.dart. Do not edit.
const sqliteWebProtocol = 1;
const sqliteWorkerBuild =
    '08f9fe59b25e0ffa41450d4dd49b75f4bff651dcdd8282e2efb21c3c6c764bba';
const sqliteWorkerFile =
    'worker-4333fc1ade0cf411bde037ede254397b42fc2225d9975f19d52c82f9c21119be.js';
const sqliteWorkerSha256 =
    '4333fc1ade0cf411bde037ede254397b42fc2225d9975f19d52c82f9c21119be';
const sqliteWasmFile =
    'sqlite3-13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4.wasm';
const sqliteWasmSha256 =
    '13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4';
const sqliteWasmIntegrity =
    'sha256-E9PxHQWzm6BhinEV+0FkCl1ItjAPXT8yX1VLQr1miKQ=';
