// Generated by tool/build_sqlite_web.dart. Do not edit.
const sqliteWebProtocol = 1;
const sqliteWorkerBuild =
    '91e8c86a459a723f2df552c1deb2fceb6578d28f2b636d4c4468a339704feef0';
const sqliteWorkerFile =
    'worker-487d3ed150511b3e57d47cf09a22fa44d0ade7839abd111693c70eca48d09a1f.js';
const sqliteWorkerSha256 =
    '487d3ed150511b3e57d47cf09a22fa44d0ade7839abd111693c70eca48d09a1f';
const sqliteWasmFile =
    'sqlite3-13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4.wasm';
const sqliteWasmSha256 =
    '13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4';
const sqliteWasmIntegrity =
    'sha256-E9PxHQWzm6BhinEV+0FkCl1ItjAPXT8yX1VLQr1miKQ=';
