// Generated by tool/build_sqlite_web.dart. Do not edit.
const sqliteWebProtocol = 1;
const sqliteWorkerBuild =
    'ce6071ece644ad5fffa944df626c410c890505dd8c287d52065c2ce8890a95b8';
const sqliteWorkerFile =
    'worker-2012ff7b2fa7a7e007e0fdb90248874f8fa222c7e76af48335a6bb61c9a6b06e.js';
const sqliteWorkerSha256 =
    '2012ff7b2fa7a7e007e0fdb90248874f8fa222c7e76af48335a6bb61c9a6b06e';
const sqliteWasmFile =
    'sqlite3-13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4.wasm';
const sqliteWasmSha256 =
    '13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4';
const sqliteWasmIntegrity =
    'sha256-E9PxHQWzm6BhinEV+0FkCl1ItjAPXT8yX1VLQr1miKQ=';
