import 'dart:convert';
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:crypto/crypto.dart';
import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

const _engineVersion = '3.6.0';
const _engineHash =
    '13d3f11d05b39ba0618a7115fb41640a5d48b6300f5d3f325f554b42bd6688a4';

// Include both sides of the worker protocol and their transitive ORM imports.
// CLI, generators and native drivers cannot invalidate this browser bundle.
Future<List<String>> sqliteWebSourcePaths({String root = '.'}) async {
  final pending = ['lib/sqlite_web_worker.dart', 'lib/src/sqlite/web.dart'];
  final sources = <String>{};
  while (pending.isNotEmpty) {
    final path = p.normalize(pending.removeLast());
    if (path == 'lib/src/sqlite/web_build.dart' || !sources.add(path)) continue;
    final unit = parseString(
      content: await File(p.join(root, path)).readAsString(),
      path: path,
    ).unit;
    for (final directive in unit.directives.whereType<UriBasedDirective>()) {
      for (final literal in [
        directive.uri,
        if (directive is NamespaceDirective)
          ...directive.configurations.map((c) => c.uri),
      ]) {
        final uri = Uri.parse(literal.stringValue!);
        if (uri.scheme == 'package' && uri.path.startsWith('orm/')) {
          pending.add('lib/${uri.path.substring('orm/'.length)}');
        } else if (uri.scheme.isEmpty) {
          pending.add(p.join(p.dirname(path), uri.toFilePath()));
        }
      }
    }
  }
  return sources.toList()..sort();
}

/// Maintainer command. Consumers use the published artifacts, without compiling.
Future<void> main(List<String> args) async {
  if (args.any((a) => a != '--check') || args.length > 1) {
    throw ArgumentError('Use --check to verify packaged SQLite web assets.');
  }
  final config = await Isolate.resolvePackageUri(
    Uri.parse('package:sqlite3/wasm.dart'),
  );
  final enginePubspec = await File.fromUri(config!.resolve('../pubspec.yaml'))
      .readAsString();
  if (!RegExp(
    '^version: $_engineVersion\$',
    multiLine: true,
  ).hasMatch(enginePubspec)) {
    throw StateError(
      'Review the SQLite WASM build when updating package:sqlite3.',
    );
  }
  final sources = [
    for (final path in await sqliteWebSourcePaths()) File(path),
    File('pubspec.yaml'),
    File('pubspec.lock'),
    File('tool/build_sqlite_web.dart'),
  ]..sort((a, b) => a.path.compareTo(b.path));
  final fingerprint = BytesBuilder();
  fingerprint.add(utf8.encode(Platform.version.split(' ').first));
  fingerprint.addByte(0);
  for (final file in sources) {
    fingerprint.add(utf8.encode(file.path));
    fingerprint.addByte(0);
    fingerprint.add(await file.readAsBytes());
    fingerprint.addByte(0);
  }
  final build = sha256.convert(fingerprint.takeBytes()).toString();
  const wasmName = 'sqlite3-$_engineHash.wasm';
  final assets = Directory('assets/sqlite');
  final engine = File('${assets.path}/$wasmName');
  final manifest = File('lib/src/sqlite/web_build.dart');
  String source(String workerHash) =>
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion)
          .format('''// Generated by tool/build_sqlite_web.dart. Do not edit.
const sqliteWebProtocol = 1;
const sqliteWorkerBuild = '$build';
const sqliteWorkerFile = 'worker-$workerHash.js';
const sqliteWorkerSha256 = '$workerHash';
const sqliteWasmFile = '$wasmName';
const sqliteWasmSha256 = '$_engineHash';
const sqliteWasmIntegrity = 'sha256-${base64Encode([for (var i = 0; i < _engineHash.length; i += 2) int.parse(_engineHash.substring(i, i + 2), radix: 16)])}';
''');
  Future<String> digest(File file) async =>
      (await sha256.bind(file.openRead()).first).toString();
  if (args.contains('--check')) {
    final current = await manifest.readAsString();
    final hash = RegExp(r"sqliteWorkerSha256\s*=\s*'([0-9a-f]{64})'")
        .firstMatch(current)
        ?.group(1);
    final worker = File('${assets.path}/worker-$hash.js');
    if (!await worker.exists() ||
        !await engine.exists() ||
        await digest(engine) != _engineHash ||
        current != source(await digest(worker))) {
      throw StateError(
        'SQLite web assets are stale. Run dart run tool/build_sqlite_web.dart.',
      );
    }
    stdout.writeln('SQLite web source, worker and WASM fingerprints match.');
    return;
  }
  await assets.create(recursive: true);
  if (!await engine.exists()) {
    final cache = File('.dart_tool/browser/sqlite3.wasm');
    if (await cache.exists() && await digest(cache) == _engineHash) {
      await cache.copy(engine.path);
    } else {
      final client = HttpClient();
      try {
        final response = await (await client.getUrl(
          Uri.parse(
            'https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-$_engineVersion/sqlite3.wasm',
          ),
        )).close();
        if (response.statusCode != 200) {
          throw StateError('WASM download: ${response.statusCode}');
        }
        final bytes = await response.fold<List<int>>(
          [],
          (all, chunk) => all..addAll(chunk),
        );
        if (sha256.convert(bytes).toString() != _engineHash) {
          throw StateError('WASM hash differs.');
        }
        await engine.writeAsBytes(bytes);
      } finally {
        client.close(force: true);
      }
    }
  }
  if (await digest(engine) != _engineHash) {
    throw StateError('Packaged WASM hash differs.');
  }
  await manifest.writeAsString(source(''));
  final temporary = Directory('.dart_tool/sqlite_web')
    ..createSync(recursive: true);
  final entry = File('${temporary.path}/worker.dart');
  await entry.writeAsString(
    "import 'package:orm/sqlite_web_worker.dart';\nvoid main() => runSqliteWebWorker();\n",
  );
  final output = File('${temporary.path}/worker.js');
  final result = await Process.run(Platform.resolvedExecutable, [
    'compile',
    'js',
    '-O2',
    '--no-source-maps',
    '--packages=.dart_tool/package_config.json',
    entry.path,
    '-o',
    output.path,
  ]);
  if (result.exitCode != 0) {
    throw StateError('${result.stdout}\n${result.stderr}');
  }
  final workerHash = await digest(output);
  final workerName = 'worker-$workerHash.js';
  final worker = File('${assets.path}/$workerName');
  await output.copy(worker.path);
  await manifest.writeAsString(source(workerHash));
  for (final file in assets.listSync()) {
    if (file is File && file.path.endsWith('.js') && file.path != worker.path) {
      await file.delete();
    }
  }
  stdout.writeln('Packaged $workerName and $wasmName.');
}
