import 'dart:io';

import 'package:orm/generate.dart';

/// Refresh checked-in clients after a generator change; historical migrations
/// remain immutable and are never regenerated by this command.
Future<void> main() async {
  final paths = <String>{'test/support/nominal/schema.dart'};
  final queries = <String>{};
  for (final directory in ['test/support', 'example']) {
    for (final file in Directory(directory).listSync(recursive: true)) {
      if (file is! File ||
          file.path.contains('/build/') ||
          file.path.contains('/.dart_tool/')) {
        continue;
      }
      if (file.path.endsWith('.orm.dart')) {
        paths.add(file.path.replaceFirst(RegExp(r'\.orm\.dart$'), '.dart'));
      } else if (file.path.endsWith('.queries.dart')) {
        queries.add(
          file.path.replaceFirst(RegExp(r'\.queries\.dart$'), '.dart'),
        );
      }
    }
  }
  for (final path in paths.toList()..sort()) {
    if (await File(path).exists()) {
      await writeGeneratedSchema(path);
      stdout.writeln('Generated $path');
    }
  }
  for (final path in queries.toList()..sort()) {
    if (await File(path).exists()) {
      await writeGeneratedQueries(path);
      stdout.writeln('Generated $path');
    }
  }
}
